// global const variables, use this.$consts.xxxx to access them in Vue
export default {
  dayMilliseconds: 8640000,
  loadingAction: [
    //(https://loading.io/animation/)
    "ld-heartbeat",
    "ld-beat",
    "ld-blink",
    "ld-bounce",
    "ld-bounceAlt",
    "ld-breath",
    "ld-wrench",
    "ld-surprise",
    "ld-clock",
    "ld-jump",
    "ld-hit",
    "ld-fade",
    "ld-flip",
    "ld-float",
    "ld-move-ltr",
    "ld-tremble",
    "ld-tick",
    "ld-move-rtl",
    "ld-move-ttb",
    "ld-move-btt",
    "ld-move-fade-ltr",
    "ld-move-fade-rtl",
    "ld-move-fade-ttb",
    "ld-move-fade-btt",
    "ld-dim",
    "ld-swing",
    "ld-wander",
    "ld-pulse",
    "ld-cycle",
    "ld-cycle-alt",
    "ld-damage",
    "ld-fade",
    "ld-flip",
    "ld-flip-h",
    "ld-flip-v",
    "ld-float",
    "ld-jelly",
    "ld-jelly-alt",
    "ld-jingle",
    "ld-measure",
    "ld-metronome",
    "ld-orbit",
    "ld-rubber-h",
    "ld-rubber-v",
    "ld-rush-btt",
    "ld-rush-ttb",
    "ld-rush-ltr",
    "ld-rush-rtl",
    "ld-shake-h",
    "ld-shake-v",
    "ld-shiver",
    "ld-skew",
    "ld-skew-alt",
    "ld-slide-btt",
    "ld-slide-ltr",
    "ld-slide-rtl",
    "ld-slide-ttb",
    "ld-smash",
    "ld-spin",
    "ld-spin-fast",
    "ld-squeeze",
    "ld-swim",
    "ld-swing",
    "ld-tick-alt",
    "ld-vortex",
    "ld-vortex-alt",
    "ld-wander-h",
    "ld-wander-v",
    "ld-shadow",
    "ld-shadow-a",
    "ld-radio",
    "ld-boradcast",
  ],
  loadingShapeSet: [
    "ld-spinner ld-clock",
    "ld-pie ld-flip",
    "ld-ball ld-bounce",
    "ld-hourglass ld-spin",
    "ld-ring ld-cycle",
    "ld-cross ld-spin-fast",
  ],
  loadingShapeColor: [
    "text-primary",
    "text-secondary",
    "text-danger",
    "text-info",
    "text-warning",
    "text-default",
    "text-success",
  ],
  XHR_STATUS_CODE: {
    SUCCESS_WITH_NO_RECORD: 3,
    SUCCESS_WITH_MULTIPLE_RECORDS: 2,
    SUCCESS_NORMAL: 1,
    DEFAULT_FAIL: 0,
    UNSUPPORT_FAIL: -1,
    FAIL_WITH_LOCAL_NO_RECORD: -2,
    FAIL_NOT_VALID_SERVER: -3,
    FAIL_WITH_REMOTE_NO_RECORD: -4,
    FAIL_NO_AUTHORITY: -5,
    FAIL_JSON_ENCODE: -6,
    FAIL_NOT_FOUND: -7,
    FAIL_LOAD_ERROR: -8,
    FAIL_TIMEOUT: -9,
    FAIL_REMOTE_UNREACHABLE: -10,
    FAIL_DB_ERROR: -11,
  },
  API: {
    XLSX: {
      LANDING: "/api/xlsx/landing.php",
      USER_IMPORT: "/api/import_user_xlsx.php",
    },
    JSON: {
      QUERY: "/api/query_json_api.php",
      PREFETCH: "/api/prefetch_json_api.php",
      STATS: "/api/stats_json_api.php",
      SWITCH: "/api/switch_json_api.php",
      USER: "/api/user_json_api.php",
      MSSQL: "/api/mssql_json_api.php",
      LXHWEB: "/api/lxhweb_json_api.php",
      AUTH: "/api/auth_json_api.php",
      IP: "/api/ip_json_api.php",
      SYSTEM: "/api/system_json_api.php",
      NOTIFICATION: "/api/notification_json_api.php",
    },
    FILE: {
      LOAD: "/api/load_file_api.php",
      EXPORT: "/api/export_file_api.php",
      XLSX: "/api/export_xlsx_api.php",
      TXT: "/api/export_tmp_txt.php",
      CSV: "/api/export_tmp_csv.php",
      DATA: "/api/export_txt_data.php",
      PHOTO: "/api/upload_user_photo.php",
      IMAGE: "/api/upload_image.php",
      BASE64: "/api/base64_image_convert.php",
    },
  },
  EVENT: {
    ERROR: "lah::global::error",
    WARNING: "lah::global::warning",
    INFO: "lah::global::info",
  },
};
